import React, { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { PageBody, PageHeader } from '../components/layout'
import { Badge, Button, Divider, EmptyState, ErrorState, Field, Icon, Panel, SegmentedControl, Select, Skeleton, Textarea, cx } from '../components/ui'
import { BarRowChart, ScoreRing, Sparkline } from '../components/charts'
import { RiskBadge } from '../components/risk'
import { ZoneDrawer } from '../components/ZoneDrawer'
import { useApp, useAsync, useDocumentTitle } from '../state/app'
import { api, endpoints } from '../lib/api'
import { bandFor, fmt, fmtDate, humanize, relative, signed } from '../lib/format'

const DETECTORS: Record<string, { what: string; why: string }> = {
  TREND_ACCELERATION: {
    what: 'Sustained upward movement in a zone score, corroborated by violation velocity',
    why: 'A single bad score is a fact; a score that keeps climbing while findings arrive faster than they close is a trajectory. Trajectories are what an inspection plan can still change.',
  },
  REPEAT_CLUSTER: {
    what: 'The same violation category recurring inside one zone',
    why: 'Repetition says the last corrective action treated the symptom. The engine already charges a repeat uplift for it, so the alert and the score agree.',
  },
  OVERDUE_ACCUMULATION: {
    what: 'Corrective actions past their committed date, counted per day',
    why: 'Overdue work is the strongest available predictor that a finding will still be open at the next inspection round.',
  },
  VERIFICATION_GAP: {
    what: 'Resolutions submitted but undecided for longer than the verification window',
    why: 'A risk cannot fall while the record is stuck in someone else’s queue. This alert names the queue, not the mine.',
  },
  INSPECTION_GAP: {
    what: 'A zone past its statutory inspection cadence',
    why: 'Uninspected time is unmeasured risk. The delay factor scores it; this alert says when to act on it.',
  },
  CROSS_FUNCTIONAL: {
    what: 'Several departments failing in the same zone at once',
    why: 'Multi-department failure in one place usually means a management or resourcing problem rather than three independent technical faults.',
  },
}

/**
 * Module 7 — AI early warning.
 *
 * The feed is generated by detectors that read the register and the engine's own
 * history series, so an alert can never contradict the map. Acknowledging is a
 * management act and is stored per detector+scope; it does not change a score,
 * and the UI says so rather than pretending otherwise.
 */
export function EarlyWarningPage() {
  const [params, setParams] = useSearchParams()
  const { boot, actor, revision, pushToast, invalidate } = useApp()
  const navigate = useNavigate()
  useDocumentTitle('Early warning · MINEGUARD AI')
  const severity = params.get('severity') ?? ''
  const mineId = params.get('mine_id') ?? ''
  const kind = params.get('kind') ?? ''
  const { data, loading, error, reload } = useAsync<any>(endpoints.alerts(new URLSearchParams(Object.entries({ severity, mine_id: mineId, kind }).filter(([, v]) => v) as any).toString()), [severity, mineId, kind, revision])
  const [drawer, setDrawer] = useState<string | null>(null)
  const [ackFor, setAckFor] = useState<string | null>(null)
  const [ackNote, setAckNote] = useState('')
  const [busy, setBusy] = useState(false)

  const alerts: any[] = data?.alerts ?? []
  const open = alerts.filter((a) => a.status !== 'ACKNOWLEDGED')
  const handled = alerts.filter((a) => a.status === 'ACKNOWLEDGED')
  const canAck = actor?.role === 'MANAGER' || actor?.role === 'ADMIN'

  const watchlist = useMemo(() => {
    const zones = boot?.zones ?? []
    return zones
      .filter((z) => !open.some((a) => a.scope_id === z.id))
      .map((z) => ({ zone: z, momentum: z.risk_score - (z.trend ?? 0) }))
      .filter((r) => r.zone.risk_score >= 30 && r.momentum > 4)
      .sort((a, b) => b.momentum - a.momentum)
      .slice(0, 6)
  }, [boot, open])

  const setQ = (key: string, value: string | null) => {
    const next = new URLSearchParams(params)
    if (!value || value === 'ALL') next.delete(key)
    else next.set(key, value)
    setParams(next, { replace: true })
  }

  const ack = async (id: string, acknowledged: boolean) => {
    setBusy(true)
    try {
      const res = await api.post<any>(`/api/alerts/${id}/ack`, { acknowledged, note: ackNote.trim() })
      pushToast({ kind: 'success', title: res.message })
      setAckFor(null)
      setAckNote('')
      reload()
      invalidate()
    } catch (e) {
      pushToast({ kind: 'error', title: 'Acknowledgement refused', body: (e as Error).message })
    } finally {
      setBusy(false)
    }
  }

  return (
    <>
      <PageHeader
        eyebrow="Module 7 · Early warning"
        title="What is becoming risky"
        subtitle="Emergence, not current state. Each warning names the detector that fired, the evidence behind it, and the movement that would clear it."
        actions={
          <>
            <Badge tone="neutral" title="Detectors run inside the API on every recompute">
              <span className="flex items-center gap-1.5">
                <Icon name="spark" className="h-3 w-3" /> {data?.engine?.mode === 'rule-based' ? 'Rule-based detectors' : 'Model detectors'}
              </span>
            </Badge>
            <Button size="sm" onClick={() => navigate('/risk')}>
              Open risk engine
            </Button>
          </>
        }
        tabs={
          <div className="flex flex-wrap items-center gap-1.5">
            <SegmentedControl
              size="sm"
              value={severity || 'ALL'}
              onChange={(v) => setQ('severity', v)}
              options={[
                { value: 'ALL', label: 'All', count: data?.total },
                { value: 'CRITICAL', label: 'Critical', count: data?.by_severity?.CRITICAL, tone: 'critical' },
                { value: 'HIGH', label: 'High', count: data?.by_severity?.HIGH, tone: 'high' },
                { value: 'MEDIUM', label: 'Watch', count: data?.by_severity?.MEDIUM, tone: 'elevated' },
              ]}
            />
            <Select className="h-7 w-[170px] text-[11.5px]" value={mineId} onChange={(e) => setQ('mine_id', e.target.value)}>
              <option value="">All mines</option>
              {boot?.mines.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.name}
                </option>
              ))}
            </Select>
            <Select className="h-7 w-[210px] text-[11.5px]" value={kind} onChange={(e) => setQ('kind', e.target.value)}>
              <option value="">All detectors</option>
              {(data?.kinds ?? []).map((k: string) => (
                <option key={k} value={k}>
                  {humanize(k)}
                </option>
              ))}
            </Select>
          </div>
        }
      />

      <PageBody className="space-y-3.5">
        <div className="grid gap-3.5 xl:grid-cols-[minmax(0,1.55fr)_minmax(0,1fr)]">
          <div className="space-y-3">
            {error && <ErrorState message={error} onRetry={reload} />}
            {loading && !data && (
              <div className="space-y-2">
                {[0, 1, 2].map((i) => (
                  <Skeleton key={i} className="h-36 w-full" />
                ))}
              </div>
            )}
            {!loading && open.length === 0 && !error && (
              <Panel title="Live warnings">
                <EmptyState
                  icon="check"
                  title="No warnings in this view"
                  body={severity || mineId || kind ? 'Nothing in the current briefing matches these filters — widen them to see the rest.' : 'No detector is firing right now: no acceleration, no repeat clusters, nothing past cadence.'}
                  action={
                    <Button size="sm" onClick={() => setParams(new URLSearchParams(), { replace: true })}>
                      Clear filters
                    </Button>
                  }
                  className="py-10"
                />
              </Panel>
            )}

            <div className="space-y-2.5">
              {open.map((a) => (
                <article key={a.id} className={cx('panel overflow-hidden', a.severity === 'CRITICAL' && 'border-[color:var(--danger)]/45')}>
                  <header className={cx('flex flex-wrap items-center gap-2 border-b px-3 py-2', a.severity === 'CRITICAL' ? 'border-[color:var(--danger)]/35 bg-[color:var(--danger)]/8' : 'border-line')}>
                    <Badge tone={a.severity === 'CRITICAL' ? 'critical' : a.severity === 'HIGH' ? 'high' : 'elevated'} dot>
                      {a.severity}
                    </Badge>
                    <span className="text-[12.5px] font-semibold">{a.title}</span>
                    <span className="text-[10.5px] text-ink-faint">
                      {a.scope_type === 'ZONE' ? a.scope_name : `${a.scope_name} · enterprise`}
                    </span>
                    <span className="ml-auto flex items-center gap-2 text-[10px] text-ink-faint">
                      <span className="font-mono">{a.id}</span>
                      <span>{relative(a.created_at)}</span>
                    </span>
                  </header>
                  <div className="p-3">
                    <div className="flex flex-wrap items-start gap-3">
                      <ScoreRing score={a.risk_score} size={62} tone={`var(--risk-${bandFor(a.risk_score).tone})`} label={a.scope_type === 'ZONE' ? 'ZONE' : 'MINE'} suffix="" />
                      <div className="min-w-[240px] flex-1">
                        <p className="text-[11.5px] leading-relaxed text-ink-dim">{a.narrative}</p>
                      </div>
                      {a.projected_impact && (
                        <div className="shrink-0 rounded border border-[color:var(--ok)]/45 bg-[color:var(--ok)]/8 px-2.5 py-2 text-right">
                          <div className="label">if cleared</div>
                          <div className="font-mono text-[13px] font-semibold" style={{ color: 'var(--risk-low)' }}>
                            {fmt(a.projected_impact.after, 1)}
                          </div>
                          <div className="text-[9.5px] text-ink-faint">
                            {a.projected_impact.action} · {signed(a.projected_impact.delta, 1)}
                          </div>
                        </div>
                      )}
                    </div>

                    <div className="mt-2.5 grid gap-1.5 sm:grid-cols-2 lg:grid-cols-3">
                      {(a.reasons ?? []).map((r: any, i: number) => (
                        <div key={i} className="rounded border border-line bg-sunken px-2 py-1.5">
                          <div className="label">{r.label}</div>
                          <div className="font-mono text-[12px] text-ink">{r.value}</div>
                          {r.delta && <div className="font-mono text-[9.5px] text-[color:var(--risk-high)]">{r.delta}</div>}
                        </div>
                      ))}
                    </div>

                    <div className="mt-2.5 rounded border border-dashed border-line px-2 py-1.5 text-[11px] leading-snug text-ink-dim">
                      <span className="label">Recommended action</span> {a.recommendation}
                    </div>

                    <div className="mt-2 flex flex-wrap items-center gap-1.5">
                      {a.scope_type === 'ZONE' && (
                        <Button size="sm" variant="primary" onClick={() => setDrawer(a.scope_id)}>
                          Investigate {a.scope_name.split(' — ')[0]}
                        </Button>
                      )}
                      <Button size="sm" variant="outline" onClick={() => navigate(`/violations?zone_id=${a.scope_id}&status=OPEN_ANY`)}>
                        Zone register
                      </Button>
                      <Button size="sm" variant="ghost" onClick={() => navigate(`/mines/${a.mine_id}`)}>
                        {a.mine_name}
                      </Button>
                      {canAck ? (
                        <Button size="sm" variant="ghost" className="ml-auto" onClick={() => setAckFor(ackFor === a.id ? null : a.id)} icon={<Icon name="check" className="h-3 w-3" />}>
                          Acknowledge
                        </Button>
                      ) : (
                        <TooltipRO role={actor?.role ?? ''} className="ml-auto" />
                      )}
                    </div>

                    {ackFor === a.id && (
                      <div className="mt-2 rounded border border-[color:var(--accent)]/40 bg-[color:var(--accent)]/6 p-2">
                        <Field label="Decision note" required hint="Stored with the alert and shown to anyone opening this briefing">
                          <Textarea rows={2} value={ackNote} onChange={(e) => setAckNote(e.target.value)} placeholder="e.g. Escalated to maintenance head; CV-2 load reduced for two shifts; DMF visit 11 Sep — risk accepted in the interim." />
                        </Field>
                        <div className="mt-1.5 flex gap-1.5">
                          <Button size="sm" variant="primary" disabled={ackNote.trim().length < 10} loading={busy} onClick={() => ack(a.id, true)}>
                            Record acknowledgement
                          </Button>
                          <Button size="sm" variant="ghost" onClick={() => setAckFor(null)}>
                            Cancel
                          </Button>
                        </div>
                      </div>
                    )}
                  </div>
                </article>
              ))}
            </div>

            {handled.length > 0 && (
              <Panel title={`Acknowledged (${handled.length})`} subtitle="Handled by a manager — the records still drive the score" dense bodyClass="p-0">
                <ul className="divide-y divide-[color:var(--line)]">
                  {handled.map((a) => (
                    <li key={a.id} className="flex flex-wrap items-center gap-2 px-3 py-2">
                      <Icon name="check" className="h-3.5 w-3.5 text-[color:var(--ok)]" />
                      <span className="text-[11.5px] font-medium">{a.title}</span>
                      <span className="text-[10.5px] text-ink-faint">{a.scope_name}</span>
                      {a.ack_note && <span className="min-w-0 flex-1 truncate text-[10.5px] text-ink-dim">“{a.ack_note}”</span>}
                      <span className="text-[10px] text-ink-faint">{fmtDate(a.acknowledged_at)}</span>
                      {canAck && (
                        <Button size="sm" variant="ghost" onClick={() => ack(a.id, false)}>
                          Reopen
                        </Button>
                      )}
                    </li>
                  ))}
                </ul>
              </Panel>
            )}
          </div>

          <div className="space-y-3">
            <Panel title="Alert load" subtitle="By severity across the whole briefing">
              <BarRowChart
                items={Object.entries(data?.by_severity ?? {}).map(([k, v]) => ({
                  label: k === 'MEDIUM' ? 'Watch' : k,
                  value: v as number,
                  tone: `var(--risk-${k === 'CRITICAL' ? 'critical' : k === 'HIGH' ? 'high' : 'elevated'})`,
                }))}
                unit=" alert(s)"
              />
              <Divider className="my-2" />
              <div className="label mb-1">By detector</div>
              <ul className="space-y-1">
                {(data?.kinds ?? []).map((k: string) => {
                  const n = alerts.filter((a) => a.kind === k).length
                  return (
                    <li key={k}>
                      <button onClick={() => setQ('kind', kind === k ? null : k)} className={cx('flex w-full items-center gap-2 rounded px-1 py-1 text-left text-[11px] transition-colors hover:bg-sunken', kind === k && 'bg-sunken')}>
                        <span className="min-w-0 flex-1 truncate text-ink-dim">{humanize(k)}</span>
                        <span className="font-mono text-ink">{n}</span>
                      </button>
                    </li>
                  )
                })}
              </ul>
            </Panel>

            <Panel title="How warnings are produced" subtitle="Detector definitions live in api/services/alerts.py and run on every recompute">
              <ul className="space-y-2">
                {Object.entries(DETECTORS).map(([k, d]) => {
                  const fired = alerts.filter((a) => a.kind === k).length
                  return (
                    <li key={k} className="rounded border border-line bg-sunken p-2">
                      <div className="flex items-center gap-2">
                        <span className="text-[11.5px] font-medium">{humanize(k)}</span>
                        {fired > 0 ? <Badge tone="elevated">{fired} firing</Badge> : <span className="text-[10px] text-ink-faint">quiet</span>}
                      </div>
                      <p className="mt-0.5 text-[10.5px] leading-snug text-ink-dim">{d.what}</p>
                      <p className="mt-0.5 text-[10px] leading-snug text-ink-faint">{d.why}</p>
                    </li>
                  )
                })}
              </ul>
              <p className="mt-2 text-[10px] leading-snug text-ink-faint">
                No predictive model is claimed here: these are explainable detectors over the register and the engine's own history. A trained model replaces this module without touching the UI once it is validated against these same records.
              </p>
            </Panel>

            <Panel title="Approaching the thresholds" subtitle="Screened from the engine's trend data — not currently alerting, but moving">
              {watchlist.length === 0 ? (
                <EmptyState icon="target" title="Nothing is accelerating" body="No zone outside the current briefing is rising fast enough to warrant a look." className="py-6" />
              ) : (
                <ul className="space-y-1">
                  {watchlist.map(({ zone, momentum }) => (
                    <li key={zone.id}>
                      <button onClick={() => setDrawer(zone.id)} className="flex w-full items-center gap-2 rounded px-1 py-1.5 text-left transition-colors hover:bg-sunken">
                        <span className="min-w-0 flex-1">
                          <span className="block truncate text-[11.5px] font-medium">{zone.name}</span>
                          <span className="block truncate text-[10px] text-ink-faint">
                            {zone.mine_name} · {zone.open_violations ?? 0} open
                          </span>
                        </span>
                        <Sparkline values={[zone.risk_score - momentum, zone.risk_score]} tone={`var(--risk-${zone.risk_tone})`} width={54} height={18} fill={false} />
                        <span className="w-10 shrink-0 text-right">
                          <RiskBadge score={zone.risk_score} />
                        </span>
                        <span className="w-[46px] shrink-0 text-right font-mono text-[10.5px] text-[color:var(--risk-high)]">{signed(momentum, 0)}</span>
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </Panel>
          </div>
        </div>
      </PageBody>

      <ZoneDrawer zoneId={drawer} onClose={() => setDrawer(null)} />
    </>
  )
}

function TooltipRO({ role }: { role: string; className?: string }) {
  return (
    <span className="ml-auto flex items-center gap-1 text-[10px] text-ink-faint" title="Acknowledging a warning is a management decision">
      <Icon name="shield" className="h-3 w-3" /> {humanize(role)} cannot acknowledge
    </span>
  )
}
